spring:
  application:
    name: event-booking-api
  datasource:
    url: jdbc:postgresql://localhost:5432/event_booking
    username: event_booking
    password: event_booking
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        serialization-mode: via_dto
        max-page-size: 100

server:
  port: 8080
